# Generated by Django 3.2.6 on 2021-08-31 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e hora do cadastro'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='tipoDeProfissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipodeprofissional', verbose_name='Tipo de Profissional'),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Data e hora da última atualização'),
        ),
        migrations.AlterField(
            model_name='tipodeprofissional',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data e hora do cadastro'),
        ),
        migrations.AlterField(
            model_name='tipodeprofissional',
            name='descricao',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipodeprofissional',
            name='situacao',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='tipodeprofissional',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Data e hora da última atualização'),
        ),
    ]
